world_of_speed/cars/urls.py
from django.contrib import admin
from django.urls import path

from world_of_speed.cars.views import CatalogueView, CarCreateView, CarDetailsView, CarEditView, CarDeleteView

urlpatterns = [
    path('catalogue/', CatalogueView.as_view(), name="catalogue"),
    path('create/', CarCreateView.as_view(), name="car create"),
    path('<int:pk>/details/', CarDetailsView.as_view(), name="car details"),
    path('<int:pk>/edit/', CarEditView.as_view(), name="car edit"),
    path('<int:pk>/delete/', CarDeleteView.as_view(), name="car delete"),
]

world_of_speed/profiles/urls.py
from django.urls import path

from world_of_speed.profiles.views import ProfileCreateView, ProfileDetailsView, ProfileEditView, ProfileDeleteView

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='profile create'),
    path('details/', ProfileDetailsView.as_view(), name='profile details'),
    path('edit/', ProfileEditView.as_view(), name='profile edit'),
    path('delete/', ProfileDeleteView.as_view(), name='profile delete'),
]

world_of_speed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('world_of_speed.web.urls')),
    path('car/', include('world_of_speed.cars.urls')),
    path('profile/', include('world_of_speed.profiles.urls')),
]

world_of_speed/web/urls.py
from django.contrib import admin
from django.urls import path

from world_of_speed.web.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name="index")
]

world_of_speed/cars/models.py
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

from world_of_speed.cars.validators import validate_year_range
from world_of_speed.profiles.models import Profile


class Car(models.Model):
    CAR_TYPES = (
        ("Rally", "Rally"),
        ("Open-wheel", "Open-wheel"),
        ("Kart", "Kart"),
        ("Drag", "Drag"),
        ("Other", "Other"),
    )

    type = models.CharField(
        max_length=10,
        null=False,
        blank=False,
        choices=CAR_TYPES
    )

    model = models.CharField(
        max_length=15,
        validators=[MinLengthValidator(1)],
        null=False,
        blank=False,
    )

    year = models.IntegerField(
        null=False,
        blank=False,
        validators=[validate_year_range]
    )

    image_url = models.URLField(
        null=False,
        blank=False,
        unique=True,
        error_messages={
            'unique': 'This image URL is already in use! Provide a new one.'},
        verbose_name="Image URL",
    )

    price = models.FloatField(
        null=False,
        blank=False,
        validators=[MinValueValidator(1.0)]
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE
    )

world_of_speed/profiles/models.py
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

from world_of_speed.profiles.validators import username_letter_validator


class Profile(models.Model):
    username = models.CharField(
        max_length=15,
        validators=[
            MinLengthValidator(3),
            username_letter_validator
        ],
        error_messages={
            'min_length': 'Username must be at least 3 chars long!'
        },
        null=False,
        blank=False,
    )

    email = models.EmailField(
        null=False,
        blank=False,
    )

    age = models.IntegerField(
        validators=[MinValueValidator(21)],
        null=False,
        blank=False,
        help_text="Age requirement: 21 years and above."
    )

    password = models.CharField(
        max_length=20,
        null=False,
        blank=False,
    )

    first_name = models.CharField(
        null=True,
        blank=True,
        max_length=25,
    )

    last_name = models.CharField(
        null=True,
        blank=True,
        max_length=25,
    )

    profile_picture = models.URLField(
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

world_of_speed/web/models.py
from django.db import models

# Create your models here.

world_of_speed/cars/forms.py
from django import forms

from world_of_speed.cars.models import Car


class CarDeleteForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = "__all__"
        exclude = ["owner"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'
            field.widget.attrs['readonly'] = True

world_of_speed/cars/views.py
from django.forms import modelform_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

from world_of_speed.cars.forms import CarDeleteForm
from world_of_speed.cars.models import Car
from world_of_speed.common.profile_helpers import get_profile


# Create your views here.
class CatalogueView(views.ListView):
    model = Car
    template_name = "car/catalogue.html"


class CarCreateView(views.CreateView):
    model = Car
    template_name = "car/car-create.html"
    fields = ["type", "model", "year", "image_url", "price"]
    success_url = reverse_lazy("catalogue")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['image_url'].widget.attrs['placeholder'] = 'https://...'
        return form

    def form_valid(self, form):
        form.instance.owner_id = get_profile().pk
        return super().form_valid(form)


class CarDetailsView(views.DetailView):
    model = Car
    template_name = "car/car-details.html"


class CarEditView(views.UpdateView):
    model = Car
    template_name = "car/car-edit.html"
    fields = ["type", "model", "year", "image_url", "price"]
    success_url = reverse_lazy("catalogue")


class CarDeleteView(views.DeleteView):
    model = Car
    template_name = "car/car-delete.html"
    success_url = reverse_lazy('catalogue')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CarDeleteForm(instance=self.object)

        return context

world_of_speed/profiles/views.py
from django import forms
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

from world_of_speed.common.profile_helpers import get_profile
from world_of_speed.profiles.models import Profile


class ProfileCreateView(views.CreateView):
    model = Profile
    template_name = 'profile/profile-create.html'
    fields = ["username", "email", "age", "password"]
    success_url = reverse_lazy('catalogue')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['password'].widget = forms.PasswordInput()
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = get_profile()
        return context


class ProfileDetailsView(views.DetailView):
    model = Profile
    template_name = 'profile/profile-details.html'

    def get_object(self, queryset=None):
        return get_profile()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_profile()
        cars = profile.car_set.all()
        total_prices = sum([car.price for car in cars])
        context['total_prices'] = total_prices
        return context


class ProfileDeleteView(views.DeleteView):
    model = Profile
    template_name = "profile/profile-delete.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        return get_profile()


class ProfileEditView(views.UpdateView):
    model = Profile
    template_name = 'profile/profile-edit.html'
    success_url = reverse_lazy('profile details')
    fields = "__all__"

    def get_object(self, queryset=None):
        return get_profile()

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields['age'].help_text = ''
        return form

world_of_speed/web/views.py
from django.shortcuts import render
from django.views import generic as views

from world_of_speed.common.profile_helpers import get_profile


# Create your views here.
class IndexView(views.TemplateView):
    template_name = 'web/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = get_profile()
        return context

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style/style.css'%}" />
    <title>WorldOfSpeed</title>
  </head>

  <body>
    <div id="box">
      <header>
        <!-- Navigation Bar -->
        <h1>
          <a class="index-navigation" href="{% url 'index' %}"
          ><span>World of Speed</span></a
        >
        </h1>
        <nav>
          <!-- if the user has not created a profile -->
   {% if not user %}
          <a href="{% url 'profile create' %}">Create Profile</a>
            {% else %}
          <!-- if the user has created a profile -->
          <a href="{% url 'catalogue' %}">Catalogue</a>
          <a href="{% url 'car create' %}">Create Car</a>
          <a href="{% url 'profile details' %}">Profile</a>
            {% endif %}
        </nav>
      </header>
        
        {% block main_content %}
        {% endblock %}
<footer>&copy;SoftUni Team 2024. All rights reserved.</footer>
    </div>
  </body>
</html>

templates/car/car-create.html
{% extends 'base.html' %}
{% block main_content %}

      <section id="create-page" class="auth">
        <!-- create car form -->
        <form id="create" method="post" action="{% url 'car create' %}">
          <div class="container">
            <h1 class="form-create-headline">Create Car</h1>
                {{ form }}
              {% csrf_token %}

            <input class="btn" type="submit" value="Create Car" />
          </div>
        </form>
      </section>
{% endblock %}

templates/car/car-delete.html
{% extends 'base.html' %}
{% block main_content %}

      <!-- delete car form -->
      <section id="delete-page" class="auth">
        <form id="delete" method="post" action="{% url 'car delete' object.pk %}" >
          <div class="container">
            <h1>Delete Car</h1>
              
              {{ form }}
              {% csrf_token %}
              
            <input class="btn submit" type="submit" value="Delete Car" />
          </div>
        </form>
      </section>

{% endblock %}

templates/car/car-details.html
{% extends 'base.html' %}
{% block main_content %}
      <!-- details section -->
      <section id="car-details">
        <h1>Car Details</h1>
        <div class="info-section">
          <div class="car-header">
            <!-- car image -->
            <img
              class="car-img"
              src="{{ object.image_url }}"
              alt="car image"
            />
            <!-- car type -->
            <h1>{{ object.type }}</h1>
            <!-- car model -->
            <p><span class="description">Model: {{ object.model }}</span></p>
            <!-- car year -->
            <p><span class="description">Year: {{ object.year }}</span></p>
            <!-- car price -->
            <p><span class="description">Price: {{ object.price|floatformat:3 }}</span></p>
          </div>

          <!-- Edit/Delete buttons -->
          <div class="buttons">
            <a href="{% url 'car edit' object.pk %}" class="edit-button">Edit</a>
            <a href="{% url 'car delete' object.pk %}" class="delete-button">Delete</a>
          </div>
        </div>
      </section>
{% endblock %}

templates/car/car-edit.html
{% extends 'base.html' %}
{% block main_content %}
      <!-- edit car form -->
      <section id="create-page" class="auth">
        <form id="create" method="post" action="{% url 'car edit' object.pk %}">
          <div class="container">
            <h1>Edit Car</h1>

              {{ form }}
              {% csrf_token %}


            <input class="btn submit" type="submit" value="Edit Car" />
          </div>
        </form>
      </section>

{% endblock %}

templates/car/catalogue.html
{% extends 'base.html' %}
{% block main_content %}

    {% if not object_list %}
      <p class="no-articles">No cars yet</p>

{% else %}
      <section id="catalogue">
        <h1>Total cars: {{ car_list.count }}</h1>
    {% for car in object_list %}

        <div class="car-card">
          <div class="image-wrap">

            <img
              src="{{ car.image_url }}"
              alt="{{ car.type }}"
            />
          </div>

          <h3>{{ car.type }}</h3>

          <h1>{{ car.model}}</h1>
          <div class="details-buttons">

            <a href="{% url 'car details' car.pk %}" class="details-btn">Details</a>
          </div>
        </div>
      {% endfor %}

      </section>
    {% endif %}
{% endblock %}

templates/profile/profile-create.html
{% extends 'base.html' %}
{% block main_content %}


      <section id="register-page" class="content auth">
        <form id="register" action="{% url 'profile create' %}" method="post">
          <div class="container">
            <div class="brand-logo"></div>
            <h1>Create Profile</h1>
            {{ form }}
              {% csrf_token %}

            <input class="btn submit" type="submit" value="Create Profile" />
          </div>
        </form>
      </section>

{% endblock %}

templates/profile/profile-delete.html
{% extends 'base.html' %}
{% block main_content %}
  <section id="create-page" class="auth">

      <div class="container">
        <h1>Are you sure you want to delete your profile?</h1>

        <form id='delete' method="post" action="{% url 'profile delete' %}">
            {% csrf_token %}


        <input class="btn submit" type="submit" value="Yes">

        </form>
      </div>
  </section>

{% endblock %}

templates/profile/profile-details.html
{% extends 'base.html' %}
{% block main_content %}
    {% load static %}

      <!-- profile details section -->
      <section id="car-details">
        <h1>Profile Details</h1>
        <div class="info-section">
          <div class="car-header">

    {% if not object.profile_picture %}
            <img
              class="car-img"
              src="{% static '/images/default-profile.png' %}"
              alt="profile-image"
            />
              {% else %}

            <img class="car-img" src="{{ object.profile_picture }}" alt="profile-image" />
              {% endif %}
            <!-- user full name (if any) -->
          {% if object.first_name or object.last_name %}
            <h1>
                {% if object.first_name %}
                {{ object.first_name }}
                {% endif %}
                {% if object.last_name %}
                {{ object.last_name }}
             {% endif %}</h1>
          {% endif %}
          


            <!-- user username -->
            <p class="description">Username: {{ object.username }}</p>
            <!-- user email -->
            <p class="description">Email: {{ object.email }}</p>
            <!-- user age -->
            <p class="description">Age: {{ object.age }}</p>
            <!-- total price of all cars -->
            <p class="description">Total price: {{ total_prices|floatformat:3 }}</p>
            <!-- Edit/Delete buttons -->
            <div class="buttons">
              <a href="{% url 'profile edit' %}" class="edit-button">Edit</a>
              <a href="{% url 'profile delete' %}" class="delete-button">Delete</a>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

templates/profile/profile-edit.html
{% extends 'base.html' %}
{% block main_content %}

      <section id="register-page" class="content auth">
        <form id="register" method="post" action="{% url 'profile edit' %}">
          <div class="container">
            <h1>Edit Profile</h1>
            {{ form }}
              {% csrf_token %}

            <input class="btn" type="submit" value="Edit Profile" />
          </div>
        </form>
      </section>
{% endblock %}

templates/web/index.html
{% extends 'base.html' %}
{% load static %}
{% block main_content %}
    
      <!-- headlines -->
      <section id="index-headline">
        <div class="index-message">
          <h2>Welcome <span>to</span> the <span>World</span> of<span>Speed</span>!</h2>
        </div>
        <img src="{% static 'images/racing-index.png' %}" alt="car" />
      </section>
{% endblock %}